Update initial readme for the repository
atlp-rwanda/commanders-rn-medica pull request #12
Opened 2024-04-30 15:48 UTC by kibongos40

# Pull Request Description:

This PR updates the README for clarity. Here's a breakdown of the changes:

- Updated about info for the repo and languages used.
- Updated installation instructions to run the app.
- Clarified usage examples for better understanding.

## Reason for Changes:

The current README was not updated and lacked clarity for the repository. These updates aim to make it easier for new users to get started with the project and know more about the project.

## Testing:

I will test the installation instructions on a clean environment to ensure accuracy after the main codebase is initialised.

## Notes for Reviewers:

Please let me know if there are any additional changes or improvements you'd like to see in the README. I'm open to feedback and suggestions to make the documentation more helpful for users.

2024-05-01 08:08 UTC, chrysloi approved these changes

2024-05-01 15:52 UTC, fredshema approved these changes

2024-05-01 15:52 UTC, fredshema approved these changes

2024-05-02 12:52 UTC, Adadie reviewed
Why do we have these settings?

2024-05-02 12:53 UTC, Adadie commented on .vscode/settings.json
> +{
Why do we have these settings?

2024-05-06 09:19 UTC, 911samuel approved these changes

2024-05-07 09:40 UTC, Adadie requested changes

2024-05-07 09:40 UTC, Adadie commented on .vscode/settings.json
> +{
cc @kibongos40

2024-05-10 13:57 UTC, twizerim approved these changes

2024-05-13 12:45 UTC, mukunzidd commented
@kibongos40 your PR targets `main` you should target `dev` instead. I'm closing this so go ahead and open a new one pointing to the proper branch.

2024-05-13 12:45 UTC, closed without merging