Feature: Patient details on book appointment
atlp-rwanda/commanders-rn-medica pull request #121
Opened 2024-06-24 20:55 UTC by Latiah

2024-06-28 11:53 UTC, fredshema approved these changes
The payment flow is working well, good job

2024-06-28 11:53 UTC, fredshema commented on app/doctor-appointments/patient-details.tsx
> +            </View>
Consider formatting your codes

2024-06-28 12:00 UTC, Latiah commented
> The payment flow is working well, good job

Thanks @fredshema

2024-06-28 12:26 UTC, Adadie commented
@Latiah @chrysloi please update the appointment prices to something that makes sense

2024-06-28 12:49 UTC, Latiah commented
> @Latiah @chrysloi please update the appointment prices to something that makes sense

@Adadie this is done

2024-06-28 13:41 UTC, 911samuel requested changes
check on the total after booking appointment and also choosing payment nothing happens Imean by placing pay with flutter button

###example
![WhatsApp Image 2024-06-28 at 15 31 05](https://github.com/atlp-rwanda/commanders-rn-medica/assets/114469939/13d5f796-3eee-4398-a7e5-4b4d81b4e46d)

2024-06-28 13:45 UTC, Latiah commented
> check on the total after booking appointment and also choosing payment nothing happens Imean by placing pay with flutter button
> 
> ### example
> ![WhatsApp Image 2024-06-28 at 15 31 05](https://private-user-images.githubusercontent.com/114469939/344184016-13d5f796-3eee-4398-a7e5-4b4d81b4e46d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1ODI2MDUsIm5iZiI6MTcxOTU4MjMwNSwicGF0aCI6Ii8xMTQ0Njk5MzkvMzQ0MTg0MDE2LTEzZDVmNzk2LTNlZWUtNDM5OC1hN2U1LTRiNGQ4MWI0ZTQ2ZC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjhUMTM0NTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2U0Yjk3NjBhMmZiN2IwYjcyMDk2YmI0YWJjNWE3ODFhN2QzYTk2ZGZlMWJmYTM4YmNjM2JlZTNmNmRjNGE1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IDEKKFG5G92LhYIXShly5fWieCHAGhtDk5pyTCsBq78)

we just resolved this thank you for your comment @911samuel

2024-06-28 13:47 UTC, Latiah commented
> > check on the total after booking appointment and also choosing payment nothing happens Imean by placing pay with flutter button
> > ### example
> > ![WhatsApp Image 2024-06-28 at 15 31 05](https://private-user-images.githubusercontent.com/114469939/344184016-13d5f796-3eee-4398-a7e5-4b4d81b4e46d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1ODI2MDUsIm5iZiI6MTcxOTU4MjMwNSwicGF0aCI6Ii8xMTQ0Njk5MzkvMzQ0MTg0MDE2LTEzZDVmNzk2LTNlZWUtNDM5OC1hN2U1LTRiNGQ4MWI0ZTQ2ZC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjhUMTM0NTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2U0Yjk3NjBhMmZiN2IwYjcyMDk2YmI0YWJjNWE3ODFhN2QzYTk2ZGZlMWJmYTM4YmNjM2JlZTNmNmRjNGE1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IDEKKFG5G92LhYIXShly5fWieCHAGhtDk5pyTCsBq78)
> 
> we just resolved this thank you for your comment @911samuel

for the payment button please check again it is on your end only

2024-07-02 13:16 UTC, 911samuel approved these changes
Great work!

2024-07-02 15:07 UTC, merged