Setup redux
atlp-rwanda/commanders-rn-medica pull request #14
Opened 2024-05-01 19:47 UTC by justinmihigo

#### What does this PR do?
Setup redux and simple demo for incrementing and decrementing a value by 1
#### Description of Task to be completed?
*Install required packages required*
- [ ] Install @reduxjs/toolkit which gives us ability to create slices and configure the stores
- [ ] Install react-redux which help us with the useDispatch and useSelector
- [ ] Simple demo
#### How should this be manually tested?
Clone the repo and npm install test using expo go or use emulators
#### Any background context you want to provide?
- Have some basics on redux to understand the simple demo

2024-05-01 21:04 UTC, 911samuel approved these changes

2024-05-02 13:06 UTC, Adadie commented
@justinmihigo rebase from dev

2024-05-02 13:18 UTC, justinmihigo commented
> @justinmihigo rebase from dev

@Adadie done

2024-05-02 17:07 UTC, Latiah approved these changes

2024-05-02 18:37 UTC, Adadie commented
Properly rebase from dev

2024-05-02 18:37 UTC, Adadie commented
Also update PR to merge to dev not main!

2024-05-02 18:52 UTC, justinmihigo commented
@Adadie done changing the base branch and I've already rebased

2024-05-04 08:02 UTC, Emmyfrank approved these changes
I can see you improved a lot , great work so far

2024-05-06 15:02 UTC, Adadie commented
@justinmihigo review with @Latiah why the build failed

2024-05-06 15:12 UTC, justinmihigo commented
the reason the build failed I think it is because there some permission I don't have to deploy to her expo because she used her account 
Build details: https://expo.dev/accounts/alatifah/projects/medica/builds/18b5c1ec-71f7-4f24-b79e-c1c88b15da58
and here is the error I am getting when I try to build locally
You don't have the required permissions to perform this operation.

This can sometimes happen if you are logged in as incorrect user.
Run eas whoami to check the username you are logged in as.
Run eas login to change the account.

Original error message: Entity not authorized: AppEntity[0f3e69b4-3214-452f-bced-5a39403b1663] (viewer = RegularUserViewerContext[3036fa27-9cbb-48ba-b09c-34bd2df7e73d], action = READ, ruleIndex = -1)
Request ID: b9c83547-e3f6-4536-90ba-74431b07f18f

2024-05-07 05:37 UTC, Emmyfrank approved these changes

2024-05-07 09:17 UTC, Adadie requested changes

2024-05-07 09:17 UTC, Adadie commented on .gitignore
This file is on the dev branch. You shouldn't be adding it there

2024-05-07 09:17 UTC, Adadie commented on app.json
shouldn't be adding this as well!!

2024-05-07 09:17 UTC, Adadie commented on app/index.tsx
Same here

2024-05-07 09:17 UTC, Adadie commented on assets/adaptive-icon.png
Same

2024-05-07 09:17 UTC, Adadie commented on package-lock.json
Remove package-lock file

2024-05-07 09:17 UTC, Adadie commented on package-lock.json
cc @justinmihigo

2024-05-07 09:17 UTC, Adadie commented on app/App.tsx
@justinmihigo  we already have our app's entry point file, named index.tsx. We shouldn't have another entry point

2024-05-07 10:16 UTC, justinmihigo commented on package-lock.json
@Adadie adadie will I remove package-lock or yarn.lock or both because we decided that we will use npm as our package manager

2024-05-08 08:19 UTC, Adadie requested changes

2024-05-08 08:19 UTC, Adadie commented on app/reduxdemo.tsx
@justinmihigo the redux provider should be wrapped around the app's entry. Which in your case is index.tsx. You can customize the file instead of creating reduxdemo file

2024-05-08 08:42 UTC, Emmyfrank approved these changes

2024-05-08 09:51 UTC, justinmihigo commented on app/reduxdemo.tsx
done

2024-05-08 15:26 UTC, Adadie approved these changes

2024-05-08 15:27 UTC, merged