Set up usefull style
atlp-rwanda/commanders-rn-medica pull request #22
Opened 2024-05-03 09:04 UTC by twizerim

### What does this pr do ?

This pr  is a configuration of css style used in our medica app , that type of css is nativewind.

### How to intall nativewind ?

       npm install nativewind
       npm install --save-dev tailwindcss@3.3.2

   or
     yarn add nativewind
    yarn add --dev tailwindcss@3.3.2

###   How is tailwind.config.js ?

      You must run npx tailwindcss init

### Modify the babel plugn
plugins: ["nativewind/babel"],

### nativewind-env.d.ts

/// <reference types="nativewind/types" /> to use templent typescripty

2024-05-03 09:59 UTC, chrysloi reviewed
- would you consider to setup the color palette we'll be using?
- also rebase your PR

2024-05-06 06:46 UTC, 911samuel commented
consider first solving conflicts

2024-05-06 11:02 UTC, justinmihigo commented
consider removing these packages 
"react-native-tailwindcss": "^1.1.11",
"tailwind-react-native-classnames": "^1.5.1"

2024-05-07 07:30 UTC, justinmihigo approved these changes
Why did you implement features when you are not done with the chore

2024-05-07 08:01 UTC, chrysloi commented
Hi @twizerim, you do need to do squash on this PR. you have around 7 commits.

2024-05-07 08:56 UTC, Emmyfrank approved these changes

2024-05-07 14:24 UTC, Adadie requested changes

2024-05-07 14:24 UTC, Adadie commented on package-lock.json
Remove this file. It's a duplicate of yarn-lock

2024-05-07 14:24 UTC, Adadie commented on app/index.tsx
> +      {/* <Appointiment/> */}
Remove comments

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/screen.tsx
We should only have files related to styles in this PR. Remove those that aren't relevant

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/reschedul.tsx
Not relevant to styles

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/appintment.tsx
Not relevant to the task of setting up styles

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/Medica/voice.png
Not relevant to the task of setting up styles

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/Medica/video.png
Not relevant to the task of setting up styles

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/Medica/quinn.png
Not relevant to the task of setting up styles

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/Medica/profile.png
Not relevant to the task of setting up styles

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/Medica/message.png
Not relevant to the task of setting up styles

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/Medica/logo.png
Not relevant to the task of setting up styles

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/Medica/keegan.png
Not relevant to the task of setting up styles

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/Medica/home.png
Not relevant to the task of setting up styles

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/Medica/history.png
Not relevant to the task of setting up styles

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/Medica/dranke.png
Not relevant to the task of setting up styles

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/Medica/drake.png
Not relevant to the task of setting up styles

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/Medica/component/checkbox.tsx
Not relevant to the task of setting up styles

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/Medica/component/cardss.tsx
Not relevant to the task of setting up styles

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/Medica/component/cards.tsx
Not relevant to the task of setting up styles

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/Medica/Raul.png
Not relevant to the task of setting up styles

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/Medica/Search.png
Not relevant to the task of setting up styles

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/Medica/More.png
Not relevant to the task of setting up styles

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/Medica/Frame.png
Not relevant to the task of setting up styles

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/Medica/Article.png
Not relevant to the task of setting up styles

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/Medica/Arrow.png
Not relevant to the task of setting up styles

2024-05-07 14:24 UTC, Adadie commented on app/Appointment/Medica/Appoint.png
Not relevant to the task of setting up styles

2024-05-07 14:25 UTC, Adadie commented
Checks are also failing

2024-05-08 08:10 UTC, Adadie commented
I believe that atleast on action should pass.  The one for build and test

2024-05-09 07:45 UTC, Adadie commented on .env
Remove package-lock.json from your .env

2024-05-09 10:08 UTC, Emmyfrank approved these changes

2024-05-09 11:13 UTC, chrysloi approved these changes
Great!

2024-05-09 12:43 UTC, 911samuel approved these changes
nice one, and i see you worked on feedback provided

2024-05-09 17:02 UTC, fredshema approved these changes

2024-05-09 17:37 UTC, merged