Add Badges to Enhance Project Visibility and Credibility.
atlp-rwanda/commanders-rn-medica pull request #25
Opened 2024-05-04 23:32 UTC by Emmyfrank

Welcome to the badge branch! 🎉

# What this branch does?

In this branch, we'll be adding badges to our GitHub repository to improve project visibility and credibility.

Here's what we'll be working on:

1. Build Status: Display whether our builds are passing or failing.
2. Code Coverage: Show the percentage of code covered by tests.
3. Dependency Status: Indicate the status of our project's dependencies.
4. License: Specify the type of license under which our project is distributed.
5. Documentation Coverage: Display the percentage of documented code.
6. Community Support: Showcase GitHub stars, forks, and open issues.

Let's make our project stand out with these badges! Contributions and ideas are welcome. Let's get started!  as code commanders🚀

2024-05-06 07:32 UTC, justinmihigo approved these changes

2024-05-06 09:23 UTC, 911samuel reviewed
consider also addding Linter badge

2024-05-06 16:59 UTC, 911samuel approved these changes

2024-05-06 17:06 UTC, Latiah approved these changes

2024-05-06 17:15 UTC, kibongos40 approved these changes

2024-05-07 09:39 UTC, Adadie requested changes

2024-05-07 09:39 UTC, Adadie commented on README.md
> +## Appwrite Badge
We won't be using appwrite on this platform

2024-05-07 10:27 UTC, Emmyfrank commented on README.md
> +## Appwrite Badge
I have alread worked on your comment , i need your review again.

2024-05-08 08:13 UTC, merged