Feat: add password reset screens
atlp-rwanda/commanders-rn-medica pull request #27
Opened 2024-05-06 13:12 UTC by fredshema

#### What does this PR do?

This PR includes designs of the forgot & reset password screens

#### Description of Task to be completed?

- Add reset password, otp verification, and new password screens
- Add navigation header component
- Add icon component
- Add typed routes configuration
- Add necessary props on button component
- Add input component

#### How should this be manually tested?

On the first page there is a link with text `Reset Password`, click it and it will redirect you to the reset password screen. Follow the continue buttons to check all screens.

#### Any background context you want to provide?

N/A

#### What are the relevant pivotal tracker/Trello stories?

N/A

#### Screenshots (if appropriate)

<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/d06aee63-56a0-4f8b-96a1-cc3ba897b5e1" width="150" />
<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/a27fe811-4469-4c6d-a0f1-841bbd892a3c" width="150" />
<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/3046d6f1-9724-44bf-8a66-4f9491c60779" width="150" />
<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/5989fe0f-a34d-44d2-ad5f-f5a8213bfdab" width="150" />
<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/eb56408f-2bef-4720-a0ab-bbf6e7b19735" width="150" />

#### Questions:

N/A

2024-05-07 13:00 UTC, Emmyfrank approved these changes

2024-05-07 13:03 UTC, chrysloi reviewed
Please remove yarn.lock as we agreed on using only npm.

2024-05-07 13:39 UTC, Emmyfrank approved these changes

2024-05-07 13:59 UTC, chrysloi approved these changes
🤝🏾

2024-05-07 15:21 UTC, 911samuel approved these changes

2024-05-09 07:51 UTC, Adadie requested changes
Also squash your commits into one

2024-05-09 07:51 UTC, Adadie commented on app/_layout.tsx
We already have the _layout file on dev. Rebase on the current changes

2024-05-09 09:51 UTC, Emmyfrank approved these changes

2024-05-09 09:55 UTC, fredshema commented
I updated the expo SDK to version 51 because it was failing to run on device. Version 50 is running in a simulator only after they updated the expo app and I can't install an earlier version of the expo app.

2024-05-09 16:57 UTC, justinmihigo approved these changes

2024-05-10 08:37 UTC, Latiah approved these changes

2024-05-10 11:24 UTC, Adadie approved these changes
Moving forward let's use native-wind styles

2024-05-10 11:24 UTC, merged