Add notifications screen and notification component design
atlp-rwanda/commanders-rn-medica pull request #32
Opened 2024-05-09 16:44 UTC by fredshema

#### What does this PR do?

This PR includes designs of the notifications screen and notification component

#### Description of Task to be completed?

- Design the notification screen with required header icons
- Design notification component

#### How should this be manually tested?

On the first page there is a link with text `Go to notifications`. It will redirect you to the notifications screen.

#### Any background context you want to provide?

N/A

#### What are the relevant pivotal tracker/Trello stories?

N/A

#### Screenshots (if appropriate)

<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/a71a523d-7f74-4da4-aaaf-3550dd7d5833" width="250" />

#### Questions:

N/A

2024-05-09 16:52 UTC, justinmihigo approved these changes
what about the new button that shows the notification status

2024-05-09 16:59 UTC, fredshema commented
> what about the new button that shows the notification status

Good catch let me add it👍🏽

2024-05-10 08:51 UTC, twizerim approved these changes

2024-05-10 11:08 UTC, mukunzidd commented
@fredshema please fix the conflicts first.

2024-05-10 11:35 UTC, mukunzidd requested changes
- Please address all the comments I made and make the notification body text more muted to improve the visual hierarchy. 
- Also leave less space between the notification details and the date so that they look like they belong together.

2024-05-10 11:35 UTC, mukunzidd commented on components/notifications/notification.tsx
@fredshema Add a way for notifications to be marked as `new`. Look at the blue text on the far right of the latest notifications on the design.

2024-05-10 11:35 UTC, mukunzidd commented on components/notifications/notification.tsx
The three dots on at the top right should have a button to clear the notifications. Just add it there. It doesn't have to be functional.

2024-05-10 11:35 UTC, mukunzidd commented on package.json
> +    "start:wsl": "REACT_NATIVE_PACKAGER_HOSTNAME=$(netsh.exe interface ip show address 'Ethernet' | grep 'IP Address' | sed -r 's/^.*IP Address:\\W*//') expo start"
Organize the scripts logically. For example all different kinds of start scripts should be together.

2024-05-15 06:43 UTC, merged