Schedule Appointment ( messaging , voice call or video call)
atlp-rwanda/commanders-rn-medica pull request #36
Opened 2024-05-10 10:49 UTC by twizerim

### What does this PR do?

This practice is related to the scheduling appointment screen UI design; those screen client will use it in scheduling doctor according to their choice of method

### Methods needed to choose:

   -  Schedule by messaging
   - Schedule by voice call
   - Schedule by video call

### Other wise:

client will be able to see appointment as completed and will be able to cancel their appointment

### Target screen that will control the client

<img width="428" alt="51_Light_my appointment upcoming" src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/136312774/25bdca40-eafd-4cc1-b4bd-f0ca4037ce2b">

2024-05-10 11:17 UTC, justinmihigo requested changes
- Can you please put the photos and icons under the assets folder separate them from the  screens,
- please work on you PR description and title for description use the template provide [here](https://github.com/atlp-rwanda/engineering-playbook/wiki/3.-Pull-Request) and remember to include the screenshots of things you worked on.
- Another thing is instead of using many card components find a way to create a typescript file to put your array of object so you can map over it. to make your codes readable
- Otherwise great work keep it up

2024-05-11 17:51 UTC, twizerim commented
making squash on appointment

2024-05-13 06:30 UTC, Emmyfrank approved these changes

2024-05-13 06:45 UTC, 911samuel approved these changes

2024-05-15 12:05 UTC, closed without merging