Feature - Articles Screens
atlp-rwanda/commanders-rn-medica pull request #37
Opened 2024-05-10 12:24 UTC by Emmyfrank

### Overview
This pull request enhances the articles feature by introducing several new screens and functionalities. It improves the user experience by providing easier access to articles and enabling bookmarking of favorite articles.

### Screens
- Added screens for displaying articles.
- Implemented navigation to view all articles.
- Implemented navigation to view detailed information for each article.
- Added a screen to display bookmarked articles.

### Checklist
- [ ] Added new screens for articles.
- [ ] Implemented navigation between screens.
- [ ] Ensured proper styling and layout for each screen.
- [ ] Implemented functionality to view all articles.
- [ ] Implemented functionality to view detailed information for each article.
- [ ] Added functionality to display bookmarked articles.

### Sceenshoot of articles

<img width="305" alt="Screenshot 2024-05-10 at 14 00 08" src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/86968559/9b1d404a-984f-4db8-9dc2-1bbaf1d8ba1c">

2024-05-10 13:52 UTC, twizerim approved these changes

2024-05-16 10:50 UTC, fredshema requested changes

2024-05-16 10:50 UTC, fredshema commented on articles/Articles.tsx
> +            <Text style={{fontSize:18,color:"#212121",fontWeight:"bold",width:230}}>{article.title2}</Text>
Is it necessary to split the title in 2 parts? The title should be one and it can wrap if the article card had a maximum width.

2024-05-16 10:50 UTC, fredshema commented on articles/Articles.tsx
> +  <Text style={styles.date}>Covid-19</Text>
Same here the article content can be one text and if the card has a maximum width value the text should wrap.

2024-05-16 10:50 UTC, fredshema commented on assets/articlesImages/Group.png
We already have this icon in `assets/icons/more-cilrcle.png`

2024-05-16 10:50 UTC, fredshema commented on assets/articlesImages/rwanda.png
Work on placing icons in the icons folder and naming them properly so that anyone can reuse them without having too many images in the project

2024-05-16 10:50 UTC, fredshema commented on assets/articlesImages/vuuu.png
This icon is also available in `assets/icons/back.png`

2024-05-16 11:03 UTC, fredshema commented
Make sure you use the right font of the app, try adding a `font-UrbanistRegular` class on your texts and see the difference.

Work on fixing the border radius of those `covid 19` chips, they are square instead of rounded. Also fix the alignment on the title and the back icon they should be centered.
<img width="180" src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/fb97c76f-76c5-4362-8347-f054040bea56"/>

Work on adding a litte space between the image and title and make sure the page has a padding so that the picture doesn't touch the screen
<img width="180" src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/51389166/0180d330-10b5-4aa8-9ea4-0ab7c459737d"/>

2024-05-17 08:32 UTC, justinmihigo approved these changes
Great work, finally you worked on fonts and padding

2024-05-17 12:43 UTC, Adadie requested changes
Improve the following ASAP:

1. Font weight of badge text.
2. Ensure that the content is aligned in the center. On my phone it's overflowing over the screen
3. Ensure that your tabs work properly and displayed data is relevant to selected tab
4. The icons for saved and search have a grayish color yet it should be black.

Check the attached screenshot of what I'm seeing for more clarity

2024-05-17 12:44 UTC, Adadie commented
![Screenshot_20240517_143407_Expo Go](https://github.com/atlp-rwanda/commanders-rn-medica/assets/68109866/3486edf6-8f96-457e-9c1f-ad7e37dade4d)
![Screenshot_20240517_143508_Expo Go](https://github.com/atlp-rwanda/commanders-rn-medica/assets/68109866/ce8ef384-ce1d-4642-b891-3f35f0e10c09)
![Screenshot_20240517_143531_Expo Go](https://github.com/atlp-rwanda/commanders-rn-medica/assets/68109866/cac00b4a-5086-4854-a1cb-bdaf0f8d6504)
![Screenshot_20240517_143553_Expo Go](https://github.com/atlp-rwanda/commanders-rn-medica/assets/68109866/8f46c47e-3d33-4cc4-9718-79b888f489c7)

2024-05-22 15:48 UTC, kibongos40 approved these changes
Great work @Emmyfrank

2024-05-23 15:36 UTC, mukunzidd requested changes
@Emmyfrank everything looks good except for the "Tabs" that are visible from the Articles List and details. Look at the figma designs.

2024-05-23 15:51 UTC, Adadie commented
> * Ensure that your tabs work properly and displayed data is relevant to selected tab

@Emmyfrank  you also haven't applied the changes requested here!
1. The sub-title font weights are still not correct
2. When I switch tabs the data doesn't change

2024-05-23 23:51 UTC, Latiah approved these changes

2024-05-23 23:52 UTC, Latiah approved these changes

2024-05-23 23:52 UTC, Emmyfrank commented
Thanks

On Fri, May 24, 2024, 1:51 AM Latifah ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/atlp-rwanda/commanders-rn-medica/pull/37#pullrequestreview-2075314576>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUXQR33MOKK62Y3T2FODA4LZDZ6H7AVCNFSM6AAAAABHQRKAOCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANZVGMYTINJXGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-24 10:57 UTC, merged