Updated splash and added onboarding screen
atlp-rwanda/commanders-rn-medica pull request #39
Opened 2024-05-10 12:42 UTC by kibongos40

# Why this pull request?
This branch has the updated splash screen and the onboarding screen.

<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/54446750/ddc06de5-d46f-443e-9476-45adc3d3ce0f" width="200" />

<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/54446750/ad17398b-9e91-41c9-be5e-3484e9be26e8" width="200" />

<img src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/54446750/3d7e673e-ee8f-40ac-a6cc-0807882e80f2" width="200"  />

2024-05-10 12:54 UTC, Emmyfrank approved these changes

2024-05-10 13:52 UTC, twizerim approved these changes

2024-05-13 13:53 UTC, mukunzidd requested changes
@kibongos40 please fix the conflicts. 

- The app breaks with a warning and an error
- Even then you ignore the error the screens do not fit the screen very well. The scroll action scrolls everything on the page while only the image and text should scroll and the button should be staying in place.

2024-05-13 14:08 UTC, kibongos40 commented
The conflicts happened because some PRs were made before mine and made the conflicts.
I'm working on the fix

2024-05-14 14:24 UTC, justinmihigo commented
resolve the conflicts and please work on your pr description and title

2024-05-15 09:37 UTC, closed without merging