Schedule Appointment screen
atlp-rwanda/commanders-rn-medica pull request #49
Opened 2024-05-15 12:38 UTC by twizerim

2024-05-15 15:29 UTC, justinmihigo requested changes
Upgrade your expo to the newest version and do the npx expo install --fix to download compatible versions of other packages

2024-05-21 12:41 UTC, Latiah commented
Hey @twizerim  kindly improve the way you mentioned on how the pr  description "How should this be manually tested?
You can use : - npm run test
- npm run build"
- tell us how we will reach the screens you worked on instead and also include other screenshoots of the screens you have in this pr

2024-05-22 06:41 UTC, justinmihigo commented
@twizerim  resolve the conflicts

2024-05-22 08:19 UTC, kibongos40 requested changes
Correct this typo on the **Yes, cancel** button

![image](https://github.com/atlp-rwanda/commanders-rn-medica/assets/54446750/757bfed3-1afe-411e-9618-7f0c16707952)

2024-05-22 20:59 UTC, Latiah commented
Awesome work @twizerim  but I did notice some parts on the screen where you did not use the font family like on the calender  and on some modals
On the modal the statement with discount it's font family is not Urbanist I guess on your implementation
![Screenshot_1716410493](https://github.com/atlp-rwanda/commanders-rn-medica/assets/99607224/078445ef-e274-4578-90c3-401316fd60f9)

![Screenshot_1716410901](https://github.com/atlp-rwanda/commanders-rn-medica/assets/99607224/a1f31e4a-f9c1-452d-bee5-f71d95ab99a3)
and the calender on the figma uses Mo, Tu ,... Su as the number of days you can change that very quickly

2024-05-22 21:00 UTC, Latiah commented
Also do remember to rebase

2024-05-23 07:37 UTC, Latiah approved these changes

2024-05-23 16:28 UTC, Adadie commented
@twizerim how do I get to your screens?

2024-05-23 16:46 UTC, Latiah commented
> @twizerim how do I get to your screens?

from the appointment tab on the home screen that's where his screens are

2024-05-23 17:48 UTC, twizerim commented
> @twizerim how do I get to your screens?

you open the tab called appointment on home screen

2024-05-24 09:56 UTC, Adadie commented
> > @twizerim how do I get to your screens?
> 
> you open the tab called appointment on home screen

The tab isn't displaying anything on my end @twizerim

2024-05-26 22:08 UTC, 911samuel approved these changes
great work bro!! things looks fine

2024-05-27 11:37 UTC, justinmihigo approved these changes
great work

2024-05-27 14:08 UTC, chrysloi requested changes
Hi @twizerim you did a good but there are a few things you might have missed please look into them.
- The tabs look different with the design
- When canceling the appointment and you select 'Yes, Cancel' the modal doesn't close after redirecting.
- on the calendar the card seems to be having much space between them
below are images showing these parts

![Simulator Screen Shot - iPhone 14 Pro Max - 2024-05-27 at 16 00 46](https://github.com/atlp-rwanda/commanders-rn-medica/assets/99283140/987298e6-1122-4479-bc1b-fa16f8b79f43)
![Simulator Screen Shot - iPhone 14 Pro Max - 2024-05-27 at 16 01 00](https://github.com/atlp-rwanda/commanders-rn-medica/assets/99283140/aaf8218f-d62f-4e4b-96be-f39778c62048)
![Simulator Screen Shot - iPhone 14 Pro Max - 2024-05-27 at 16 01 43](https://github.com/atlp-rwanda/commanders-rn-medica/assets/99283140/59f288ea-bcf7-4529-9216-9347ff92a05a)

2024-05-27 16:37 UTC, Adadie requested changes
@twizerim here is  the feedback I shared with you on the call, just for your reference:

1. The tabs for Ongoing, Completed and Cancelled should have a greyish color and the font-weight should be slightly higher.
2. The top margin at the Reschedule Appointment title is quite high.
3. Correct typos across all the screens
4. Remove the prefilled data in the text-area
5. Text in the text-area should be greyish
6. Reduce the spacing between the hour selection buttons

You may also refer to the screenshots below:
![Screenshot_20240527_175008_Expo Go](https://github.com/atlp-rwanda/commanders-rn-medica/assets/68109866/a3107692-469f-4e0e-8b25-895bb1947457)
![Screenshot_20240527_175008_Expo Go](https://github.com/atlp-rwanda/commanders-rn-medica/assets/68109866/a3107692-469f-4e0e-8b25-895bb1947457)
![Screenshot_20240527_174659_Expo Go](https://github.com/atlp-rwanda/commanders-rn-medica/assets/68109866/d2a88752-36c3-416f-8229-996f000ad4c6)
![Screenshot_20240527_174659_Expo Go](https://github.com/atlp-rwanda/commanders-rn-medica/assets/68109866/d2a88752-36c3-416f-8229-996f000ad4c6)
![Screenshot_20240527_174359_Expo Go](https://github.com/atlp-rwanda/commanders-rn-medica/assets/68109866/add30a14-4c94-488f-ba17-7bea571ae12c)
![Screenshot_20240527_174359_Expo Go](https://github.com/atlp-rwanda/commanders-rn-medica/assets/68109866/add30a14-4c94-488f-ba17-7bea571ae12c)
![Screenshot_20240527_175233_Expo Go](https://github.com/atlp-rwanda/commanders-rn-medica/assets/68109866/0ee867a8-e0db-4fe2-9a80-240e5629970c)
![Screenshot_20240527_175233_Expo Go](https://github.com/atlp-rwanda/commanders-rn-medica/assets/68109866/0ee867a8-e0db-4fe2-9a80-240e5629970c)
![Screenshot_20240527_175104_Expo Go](https://github.com/atlp-rwanda/commanders-rn-medica/assets/68109866/eea2d176-3807-46a6-96d4-e466c2d2cfda)
![Screenshot_20240527_175104_Expo Go](https://github.com/atlp-rwanda/commanders-rn-medica/assets/68109866/eea2d176-3807-46a6-96d4-e466c2d2cfda)
![Screenshot_20240527_175252_Expo Go](https://github.com/atlp-rwanda/commanders-rn-medica/assets/68109866/58fb5a37-6d15-4862-93b8-638d1c7aa3d7)
![Screenshot_20240527_175252_Expo Go](https://github.com/atlp-rwanda/commanders-rn-medica/assets/68109866/58fb5a37-6d15-4862-93b8-638d1c7aa3d7)

2024-05-28 15:16 UTC, Adadie requested changes
Hey @twizerim awesome work. I like the improvements.
Would you please remove the assets that are already in the repo

2024-05-29 08:41 UTC, Adadie requested changes

2024-05-29 08:41 UTC, Adadie commented on assets/appointmentIcon/first.png
I believe you should already have this on dev

2024-05-29 08:41 UTC, Adadie commented on assets/history.png
This as well

2024-05-29 08:41 UTC, Adadie commented on assets/home.png
Also this

2024-05-29 08:41 UTC, Adadie commented on assets/profile.png
Also this is on dev

2024-05-29 08:41 UTC, Adadie commented on assets/appointmentIcon/Group1.png
Also this is on dev

2024-05-29 08:41 UTC, Adadie commented on assets/appointmentIcon/Arrow.png
Also this is on dev

2024-05-29 08:41 UTC, Adadie commented on assets/Appoint.png
Also this is on dev

2024-05-29 08:41 UTC, Adadie commented on assets/Article.png
Also this is on dev

2024-05-29 09:44 UTC, twizerim commented on assets/Article.png
assets/appointmentIcon/first.png  and  assets/appointmentIcon/Group1.png are not found in dev because they are required  in my task only and others can be removed

2024-05-29 11:57 UTC, merged