Feature: doctor appointment payment screens
atlp-rwanda/commanders-rn-medica pull request #69
Opened 2024-05-22 18:59 UTC by fredshema

#### What does this PR do?

This PR includes designs of payment screens for the doctor appointment screens

#### Description of Task to be completed?

- Design select payment methods screen
- Design add new card screen
- Design summary screen
- Design success & failed state screens

#### How should this be manually tested?

Navigate to the home page and scroll down. Click on one doctor to view their details. Click next button until you get to the payments screen. Click add new card to see the screen for adding a new card. Go back and click Next to see summary of the payments and click next to input your pin. After clicking next you should see a success modal.

#### Any background context you want to provide?

N/A

#### What are the relevant pivotal tracker/Trello stories?

N/A

#### Screenshots (if appropriate)

#### Questions:

N/A

2024-05-23 04:03 UTC, twizerim approved these changes

2024-05-23 11:58 UTC, Latiah approved these changes

2024-05-23 12:03 UTC, Latiah commented
Everything looks good on my end  but if you would consider displaying the date as it is on the figma design it would be nice and also add the screen for when the appointment failed I did not see it

![Screenshot_1716465752](https://github.com/atlp-rwanda/commanders-rn-medica/assets/99607224/6f782e2a-189c-4650-8afb-b0f47835eb61)

2024-05-23 13:43 UTC, fredshema commented
@Latiah fixed those issues and to test the failed modal first go to the pin page enter pin and click continue after it shows you the success modal and then click next and continue again and you should see the failed modal.

2024-05-24 09:44 UTC, Adadie requested changes
@fredshema apply the following changes ASAP

- When I add a card I should be redirected to the screen with the MasterCard payment method
- the font weights on the payments page are off.
- when I complete the payments, I get an success error message due to routing

You may refer to the screenshots below:
- https://app.snippyly.com/discuss?q=LSJaHieBGXppc9OhrjRa
- https://app.snippyly.com/discuss?q=Hx87d74XBNwG9jsnyjn8&EDIT=tWw4iG9GxfqkvKuPmphe 
![WhatsApp Image 2024-05-24 at 11 28 07](https://github.com/atlp-rwanda/commanders-rn-medica/assets/68109866/d3447f88-d753-447d-adb2-9ac0a3dbdefb)

2024-05-24 11:24 UTC, merged