Feature:Reset password with email implementation
atlp-rwanda/commanders-rn-medica pull request #93
Opened 2024-06-11 00:02 UTC by Latiah

**What does this PR do?**
This PR includes the implementation of the reset password for registered users where an otp is sent to their  email s so that it can be used for reseting the password.

**Description of Task to be completed?**
Modify the email template on supabase 
make the select method screen display email 
increase the number of input fields for the otp as supabase was providing 6 digits

**How should this be manually tested?**
Navigate to the sign in page and enter your email then click on the forgot password and you will be directed to a screen where you will chose the method you want to use to reset your password  and from this screen you will be directed to fill in the otp which is the one you received on your email after filling it in you will go to a screen of setting a new password and after entering your new password and confirming it a modal will pop up confirming that your password is set and then you will be redirected to the home screen 
 
**Any background context you want to provide?**
First sign up before using your email to reset the password because if it is not registered you will not receive the token you can use to reset your password on that email

What are the relevant pivotal tracker/Trello stories?
N/A

2024-06-11 12:53 UTC, 911samuel approved these changes
Amazing work

2024-06-12 10:29 UTC, twizerim approved these changes

2024-06-12 15:47 UTC, Adadie commented
Hey @Latiah I'm unable to add an email I want to remember the password for. Find below a screenshot of what I'm seeing:
![Screenshot_20240612_174441_Expo Go](https://github.com/atlp-rwanda/commanders-rn-medica/assets/68109866/a4cf29de-2d53-4a68-a78c-fc5309b5eb92)

2024-06-12 15:51 UTC, Latiah commented
> Hey @Latiah I'm unable to add an email I want to remember the password for. Find below a screenshot of what I'm seeing: ![Screenshot_20240612_174441_Expo Go](https://private-user-images.githubusercontent.com/68109866/339040997-a4cf29de-2d53-4a68-a78c-fc5309b5eb92.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDc1MzIsIm5iZiI6MTcxODIwNzIzMiwicGF0aCI6Ii82ODEwOTg2Ni8zMzkwNDA5OTctYTRjZjI5ZGUtMmQ1My00YTY4LWE3OGMtZmM1MzA5YjVlYjkyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE1NDcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1YjVjODAwZDg2NWRlOWJiM2JjMTMyZjYyNmZhNjdlNjM3NzA4YTgzZDMxNWIyYTQyNzUwMWM1ODQ3M2M5ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X8u7DDLURStdlPQRpy9feZmrqI9efwZWyPFRoviTBEY)

you had to enter it on the sign in screen

2024-06-12 15:52 UTC, Latiah commented
> > Hey @Latiah I'm unable to add an email I want to remember the password for. Find below a screenshot of what I'm seeing: ![Screenshot_20240612_174441_Expo Go](https://private-user-images.githubusercontent.com/68109866/339040997-a4cf29de-2d53-4a68-a78c-fc5309b5eb92.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDc1MzIsIm5iZiI6MTcxODIwNzIzMiwicGF0aCI6Ii82ODEwOTg2Ni8zMzkwNDA5OTctYTRjZjI5ZGUtMmQ1My00YTY4LWE3OGMtZmM1MzA5YjVlYjkyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE1NDcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1YjVjODAwZDg2NWRlOWJiM2JjMTMyZjYyNmZhNjdlNjM3NzA4YTgzZDMxNWIyYTQyNzUwMWM1ODQ3M2M5ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X8u7DDLURStdlPQRpy9feZmrqI9efwZWyPFRoviTBEY)
> 
> you had to enter it on the sign in screen

Also first register cause I used a different project if you registered on Sam's that does not count

2024-06-12 21:05 UTC, Emmyfrank approved these changes
nice work, you have worked on my comments

2024-06-12 21:05 UTC, Emmyfrank commented on app/reset-password/index.tsx
i think you can try to work on these three simple changes
when you click on email field , the keyboard comes up and hide the email field and is hard to see what you are typing
# before your type your email
<img width="327" alt="Screenshot 2024-06-12 at 21 03 08" src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/86968559/f369fa9e-f779-4dd9-a4cd-381c11796837">
#after when you start typing your email
<img width="333" alt="Screenshot 2024-06-12 at 21 03 24" src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/86968559/5b7c414a-70df-4f9a-b00b-17e328696c4b">
# I am also getting this network error on my end while my network is strong
<img width="681" alt="Screenshot 2024-06-12 at 21 03 49" src="https://github.com/atlp-rwanda/commanders-rn-medica/assets/86968559/c8330353-7d98-470b-b14a-659ff54b2aea">

2024-06-12 21:08 UTC, Latiah commented
@Adadie worked on the comments you gave.

2024-06-13 12:22 UTC, Adadie requested changes
Hey @Latiah awesome work on the implementation. Here's a few things you improve to make it much better:

1. Reduce the resend otp link time to not more than 2 minutes. It doesn't provide a good user experience for the user to wait for a whole hour to be able to resend
2. Add loading states across all the functionalities. Also, when a request is loading I should not be able to submit another request i.e I received two OTP emails because I clicked the button multiple times.
3. When I've changed my password I should not be able to go back to that screen for changing password. The auth session should also be clear, I was able to change my password multiple times by going back at that screen.

Let me know if all this makes sense to you

2024-06-13 12:29 UTC, Latiah commented
> Hey @Latiah awesome work on the implementation. Here's a few things you improve to make it much better:
> 
> 1. Reduce the resend otp link time to not more than 2 minutes. It doesn't provide a good user experience for the user to wait for a whole hour to be able to resend
> 2. Add loading states across all the functionalities. Also, when a request is loading I should not be able to submit another request i.e I received two OTP emails because I clicked the button multiple times.
> 3. When I've changed my password I should not be able to go back to that screen for changing password. The auth session should also be clear, I was able to change my password multiple times by going back at that screen.
> 
> Let me know if all this makes sense to you

Let me work on them very quickly

2024-06-13 15:13 UTC, Latiah commented
@Adadie  I worked on these comments you provided you can check again.

2024-06-14 07:00 UTC, merged